### ISSUE TITLE
Separate plugin project?

### ISSUE THREAD

**Issue by slhck** [bufferoverflow/verdaccio-gitlab#102]
Great job on this project! I was just wondering … the Docker Compose file specifically includes GitLab, but there might be a use case (and perhaps it's more common) where a GitLab instance already exists, and one would just like to run Verdaccio with the plugin. Or, you'd just like to add the plugin to an existing Verdaccio instance. Do you think it would make sense to split this project into a dedicated project for the plugin, and one combining the plugin with Verdaccio (and, optionally, GitLab)?

**Comment by bufferoverflow** [comment]
Thanks for the feedbakc!
The verdaccio plugin can be installed via npm, there is a docker image you can use to have verdaccio with this plugin up and running, see https://github.com/bufferoverflow/verdaccio-gitlab#docker (custom configuration options are also possible). The docker-compose file is for testing and demo purpose. So I do not really see what's missing. Please reopen if you need more details.
