### ISSUE TITLE
how to handle group owner ship changes? timeout?

### ISSUE THREAD

**Issue by bufferoverflow** [bufferoverflow/verdaccio-gitlab#11]

**Comment by dlouzan** [comment]
Currently there's two cases:
- if not using the auth cache, every request is checked against gitlab and the group ownership checked, no issues, ownership changes are immediately detected
- if using the auth cache, then the configured ttl applies (default: 300 seconds)

**Comment by dlouzan** [comment]
@bufferoverflow Can this be closed?
