### ISSUE TITLE
Adding plugin to existing verdaccio

### ISSUE THREAD

**Issue by suenot** [bufferoverflow/verdaccio-gitlab#118]
How add this plugin to existing verdaccio?

**Comment by juanpicado** [comment]
@suenot what do you mean with 'add' ? as dependency or something else?

**Comment by suenot** [comment]
How it realized in [verdaccio official documentation](https://verdaccio.org/docs/en/plugins).
Like as: ```npm install --global verdaccio-gitlab```

**Comment by juanpicado** [comment]
Ok cool, :) then problem solved. I'm closing this.
