### ISSUE TITLE
Allow limiting access to only authenticated users

### ISSUE THREAD

**Issue by drubin** [bufferoverflow/verdaccio-gitlab#2]
Related to https://github.com/bufferoverflow/verdaccio-gitlab/pull/1 

It would be great to limit who has access to view the npm packages that are published. 

Currently even adding `access: $authenticated` doesn't limit access.

**Comment by bufferoverflow** [comment]
you are welcome to test this with 0.0.5 , please close the issue if it works properly on your side.

**Comment by drubin** [comment]
@bufferoverflow Thank you for adding this so quickly, Your fix is much better than mine.
