### ISSUE TITLE
Uppercase authentication issue

### ISSUE THREAD

**Issue by YoannMa** [bufferoverflow/verdaccio-gitlab#20]
It seems you check the username in the login with case sensitivity

NPM CLI ask you to login with a lowercase username
Gitlab doesn't allow you to have the same username with a different case

So if you have an username with an uppercase, you can login in the Web UI but not in the CLI.

**Comment by dlouzan** [comment]
The current logic is to pass directly whatever is provided, without any casing conversion, yes.

We could apply the logic that all operations in the npm registry apply a lowercase function to the provided data. Now my question is: how does gitlab react to this? What if a user is registered with uppercase? do both variants map to the same user? are the gitlab libraries ok with any of the variants?

I did a quick googling and didn't find a clear answer, whether gitlab accepts uppercase characters, or the policy to apply.

/cc @bufferoverflow @ercanucan

**Comment by dlouzan** [comment]
I just tried registering `USER` in my local gitlab:
- That worked, with uppercase
- The system does not allow me now to setup another user with the same characters as lowercase

But when I try to login in npm with the lowercase version, gitlab rejects the login with invalid credentials.

Sooo, what is the correct approach here? Is there any settings / policy in gitlab to convert different case usernames?

**Comment by YoannMa** [comment]
Indeed, I thought you could login on Gitlab with a different case, but it seems you can't.

So the issue isn't from verdaccio nor this plugin, it comes from either the NPM CLI lowering the username or Gitlab not testing against lowercase.

**Comment by dlouzan** [comment]
@bufferoverflow I think we can close this, not much we can do on this end, but it's worth keeping in mind this limitation

**Comment by bufferoverflow** [comment]
I was think again about this and the #103 PR. If we allow this we need a configuration flag, e.g. something like `userCaseSensitive` which will be enabled by default. Otherwise people could publish things that should belong to others. e.g. publish to group `good` with username `Good` is not that nice.

/cc @GFWagnitz @lando-cal

**Comment by lando-cal** [comment]
> Otherwise people could publish things that should belong to others. e.g. publish to group `good` with username `Good` is not that nice.
> 
> /cc @GFWagnitz @lando-cal

Unfortunately, I don't have the time to implement that. While I'm happy to contribute alterations to any projects I work with professionally, sustained development on exterior projects is a tough sell while working in the public sector. Oh, how I do miss the pace of start-ups now and then!

Anyhow, I'm happy to test any further revisions in our environment, and send up any resulting tweaks, but this project would be best served by someone else overseeing this issue from here.

**Comment by GFWagnitz** [comment]
> Otherwise people could publish things that should belong to others. e.g. publish to group `good` with username `Good` is not that nice.
> 
> /cc @GFWagnitz @lando-cal

Agreed, I can implement the config flag no problem until next week and add on the #103 PR.

**Comment by Telokis** [comment]
@bufferoverflow Is this something that could really occur?

**Comment by GFWagnitz** [comment]
@bufferoverflow @Telokis Actually I just noticed can't happen. If you try to create an account with an username that already is a group it says "username already taken", and the other way is also true. If you try to name a group with an existing username it says "group name already taken". And of course it is this way because of conflict on the URL, since user and group URL are case insensitive.

**Comment by bufferoverflow** [comment]
Thank's for clarification @GFWagnitz ! I've merged your PR.

**Comment by Telokis** [comment]
Can't there be an issue with the user "display name"?

For example, my username could be "telokis" and that's what I would use to login but my display name could be "Good".
Depending on the way verdaccio-gitlab handle this, it could allow me to access the "Good" group as if it were mine.

I don't think it's the case but I want to be sure.

**Comment by bufferoverflow** [comment]
@Telokis We do not use the display name so should not be an issue. But I agree you can put whatever name as display name and the URL and username will be the only thing to trust.
