### ISSUE TITLE
Question: Should scope checking be case insensitive ?

### ISSUE THREAD

**Issue by 2Kable** [bufferoverflow/verdaccio-gitlab#50]
Currently scope checking is case sensitive in [verdaccio.js](https://github.com/bufferoverflow/verdaccio-gitlab/blob/435521bd866e3306cce5207ca48cf4262e7a99f0/src/gitlab.js#L174)

I usually create project and group in gitlab with an uppercase, gitlab by default create the url with the same casing. 

Since lowercase URL are redirected, and group creation checks are not case sensitive (so for `GroupA`, I can't create `groupa`), we could maybe check the group and scope name as lowercase ?

**Comment by bufferoverflow** [comment]
This makes sense, you can provide a MR if you like

**Comment by bufferoverflow** [comment]
user is cas incensitive now, see https://github.com/bufferoverflow/verdaccio-gitlab/pull/103/files
