### ISSUE TITLE
Authentication using SSH keys/tokens

### ISSUE THREAD

**Issue by marco-silva0000** [bufferoverflow/verdaccio-gitlab#51]
My team uses ssh keys for pulling and pushing from gitlab.com, and I've made a docker integration that copies those from the user's .ssh folder to the docker environment, gets the private projects and moves on.

We are now experimenting with using verdaccio instead of git for som sub projects and components, and I have it working with PAT, but I can't have this in an automated way, unless we implement some standard for storing the user's name and token.

It would be nice for verdaccio gitlab to work with either SSH keys or deploy keys as an authentication method for this use case, I'm not sure if the gitlab.com infrastructure would allow such thing, but I think many users would appreciate it.

**Comment by dlouzan** [comment]
Gitlab does not support [interacting with the API](https://docs.gitlab.com/ce/api/README.html#authentication) with ssh keys by definition, those are used for ssh connections and the API is REST HTTP.
