### ISSUE TITLE
Custom gitlab url

### ISSUE THREAD

**Issue by nest-aka-swan** [bufferoverflow/verdaccio-gitlab#52]
Currently Dockerfile doesn't provide a way to override gitlab url because it intended to be used with own gitlab instance running via docker-compose.yml.

I think it would be great if Dockerfile allow you to use verdaccio-gitlab plugin with remote gitlab instance

**Comment by dlouzan** [comment]
I'm not sure I understand your issue; the Dockerfile just uses a default `conf/docker.yaml` and copies it to the expected location of the config file for verdaccio under `/verdaccio/conf/config.yaml`. This is what is used in the docker-compose file.

If you want to overwrite the gitlab location, just provide a custom configuration file and mount it at that location on docker startup with the `--volume` option. If you are on e.g. a kubernetes environment, it's even easier with the native volumes support.

**Comment by dlouzan** [comment]
#53 documents this in the readme
