### ISSUE TITLE
verdaccio 3.x dependencies used in package.json but docker builds on top of 4.x

### ISSUE THREAD

**Issue by dlouzan** [bufferoverflow/verdaccio-gitlab#66]
There might be incompatibilities since the dependencies in package.json reference 3.x, but the docker image builds on top of verdaccio's 4.x image.

As of today we haven't experienced it and I haven't seen any changes to the API signatures in the 4.x feature list, but it could happen.

Reported by @blackholegalaxy in #65

**Comment by bufferoverflow** [comment]
now everything is on 4
