### ISSUE TITLE
What are the risks of using it on production?

### ISSUE THREAD

**Issue by EmadMokhtar** [bufferoverflow/verdaccio-gitlab#70]
I can see **This is experimental!** when I open the repo, Is this mean this is not ready for production? and if it is ready and used in production, what are the risks of using it?

**Comment by bufferoverflow** [comment]
There are no special load tests or production environment with a large amount of users. However, I added the statement *This is experimental!* long time ago during initial release and since we fixed a lot of bugs and added test suites etc.

/cc @dlouzan What do you think?
