### ISSUE TITLE
error authenticating user

### ISSUE THREAD

**Issue by ddsultan** [bufferoverflow/verdaccio-gitlab#80]
I am using our company's private Gitlab server for authentication and getting this error: `error querying gitlab user data: Cannot read property 'headers' of undefined`. I tried to change the log level of `verdaccio` to `trace` to log more information but it does not help much. What could be the problem? The logs from the plugin are not giving me pertinent information. 

Any help would be really apprciated.

P.S: It might be because of the self-signed SSL certificate of the server. I have checked the Gitlab REST API on the server with `curl` but I got this `SSL certificate problem: unable to get local issuer certificate`. I made it work passing `-k`.

node: **v8.11.1**
verdaccio: **4.0.1**
verdaccio-gitlab: **v2.2.0**

**Comment by bufferoverflow** [comment]
might be related to this https://github.com/bufferoverflow/verdaccio-gitlab/issues/15
