### ISSUE TITLE
Migrate plugin to TypeScript and remove flow-type

### ISSUE THREAD

**Issue by dlouzan** [bufferoverflow/verdaccio-gitlab#83]
As suggested by @juanpicado in Discord's general channel, all core plugins are moving out of flow-type and been migrated to TypeScript.

I think it would make sense to migrate and @bufferoverflow and me also were not that impressed by flow's flow (lol).

**Comment by bufferoverflow** [comment]
I would love to see this and contributions to get it done.

**Comment by juanpicado** [comment]
:) I have time ...

**Comment by bufferoverflow** [comment]
awesome @juanpicado did it, thank you so much!
