### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by atton16** [bufferoverflow/verdaccio-gitlab#85]
Hi, I install this package using `docker pull bufferoverflow/verdaccio-gitlab:latest` and I got the image which is built 8 days ago. It seems that something is broken, the web page loaded in plain white. I have been using this package for months and this is the first time I updated it and not the web app is broken. Please help.

<img width="1440" alt="Screen Shot 2019-07-05 at 20 43 18" src="https://user-images.githubusercontent.com/5247367/60726473-d5439480-9f65-11e9-9f0e-ad1e88156d54.png">

**Comment by atton16** [comment]
It appears that if the `config.yaml` file contains **apostrophe** character the UI will fail to initialize. I am working around by simple change the string to not contain such character.

For the sake of development, I will leave this issue opened.

**Comment by dlouzan** [comment]
Hello @atton16, this might be the same issue as #82, but I'm still not able to reproduce it :-?

I have just pulled the same docker image and started it, no exceptions in the browser logs when loading the UI.

Could you maybe give some more detailed info about your env and how do you trigger this?

**Comment by dlouzan** [comment]
And by the way I just used the stock config in the image, which contains apostrophes for some entries, no issues.

**Comment by atton16** [comment]
> And by the way I just used the stock config in the image, which contains apostrophes for some entries, no issues.

Well, can you please try with `title` like `"atton16's test registry"`

**Comment by dlouzan** [comment]
Ah ok, sorry, I misunderstood your report :-) We might have some error in the parsing (or maybe verdaccio itself, since I don't recall that we parse that directly ourselves)

**Comment by bufferoverflow** [comment]
seems not related to verdaccio-gitlab
